site_name: Roman Lutz
extra:
  name: Roman Lutz
  titles:
    - Responsible AI Engineering Lead
    - AI Red Teaming
    - Trust and Safety
    - Open Source

theme:
  name: null
  custom_dir: 'custom_theme/'
